Name:           ros-indigo-rqt-wrapper
Version:        0.1.3
Release:        0%{?dist}
Summary:        ROS rqt_wrapper package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/rqt_wrapper
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-python-qt-binding
Requires:       ros-indigo-qt-gui-py-common
Requires:       ros-indigo-rocon-console
Requires:       ros-indigo-rocon-python-utils
Requires:       ros-indigo-rosgraph
Requires:       ros-indigo-rqt-gui
Requires:       ros-indigo-rqt-gui-py
Requires:       ros-indigo-rqt-plot
Requires:       ros-indigo-rqt-reconfigure
Requires:       ros-indigo-rqt-robot-monitor
BuildRequires:  ros-indigo-catkin

%description
A wrapper for keeping rqt programs alive.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Aug 29 2016 Daniel Stonier <d.stonier@gmail.com> - 0.1.3-0
- Autogenerated by Bloom

* Mon Aug 29 2016 Daniel Stonier <d.stonier@gmail.com> - 0.1.2-0
- Autogenerated by Bloom

